import type { Product, ProductDisplaySettings, Promotion, TerminalSettings } from '../types/menu';
import { escapeHtml, imageStyle } from '../utils/helpers';

type AdminTab = 'terminal' | 'menu' | 'promotions' | 'staff' | 'quality' | 'audit';
const tabs: Array<[AdminTab, string]> = [['terminal', 'Терминал'], ['menu', 'Витрина'], ['promotions', 'Баннеры'], ['staff', 'Официанты'], ['quality', 'Проверка iiko'], ['audit', 'Журнал']];
const options = (products: Product[], selected = '') => products.map((item) => `<option value="${escapeHtml(item.id)}" ${item.id === selected ? 'selected' : ''}>${escapeHtml(item.category)} · ${escapeHtml(item.name)}</option>`).join('');
const multipleOptions = (products: Product[], selected: string[] = []) => products.map((item) => `<option value="${escapeHtml(item.id)}" ${selected.includes(item.id) ? 'selected' : ''}>${escapeHtml(item.category)} · ${escapeHtml(item.name)}</option>`).join('');
const missing = (products: Product[]) => ({ description: products.filter((item) => !item.description).length, kbju: products.filter((item) => !item.kbju).length, pairs: products.filter((item) => !item.pairs_with?.length).length });

type IikoEmployee = { employee_id: string; display_name: string; role_name: string; is_active: boolean };
type Waiter = { id: string; display_name: string; is_active: boolean; iiko_employee_id: string | null; role_name?: string; iiko_active?: boolean };
export function adminPage(products: Product[], promotions: Promotion[], display: Record<string, ProductDisplaySettings>, terminal: TerminalSettings | null, tab: AdminTab, selectedId: string | null, audit: Array<{ action: string; entity: string; entity_id: string; created_at: string }> = [], employees: IikoEmployee[] = [], waiters: Waiter[] = []) {
  const selected = products.find((item) => item.id === selectedId) ?? products[0];
  const stats = missing(products);
  const terminalView = `<section class="admin-panel admin-terminal">
    <div class="admin-panel__intro"><span class="eyebrow">ПРИВЯЗКА ПЛАНШЕТА</span><h2>Этот терминал</h2><p>Стол сохраняется для этого планшета и автоматически добавляется к каждому заказу.</p></div>
    <div class="terminal-form">
      <label>Название планшета<input data-admin-terminal="label" value="${escapeHtml(terminal?.label ?? '')}" placeholder="Например: Основной зал"></label>
      <label>Номер стола<input data-admin-terminal="tableNumber" value="${escapeHtml(terminal?.tableNumber ?? '')}" placeholder="Например: 14" inputmode="numeric"></label>
      <label>Таймаут бездействия<select data-admin-terminal="idleSeconds"><option value="45" ${(terminal?.idleSeconds ?? 45) === 45 ? 'selected' : ''}>45 секунд</option><option value="60" ${terminal?.idleSeconds === 60 ? 'selected' : ''}>1 минута</option><option value="90" ${terminal?.idleSeconds === 90 ? 'selected' : ''}>1,5 минуты</option><option value="120" ${terminal?.idleSeconds === 120 ? 'selected' : ''}>2 минуты</option></select></label>
      <label class="admin-switch"><input type="checkbox" data-admin-terminal="isActive" ${terminal?.isActive !== false ? 'checked' : ''}><span></span> Терминал принимает заказы</label>
      <button class="button button--primary" data-action="save-terminal">Сохранить терминал</button>
    </div>
    <div class="admin-app-update"><div><span class="eyebrow">ОБНОВЛЕНИЕ ПРИЛОЖЕНИЯ</span><h3>Актуальная версия интерфейса</h3><p>Скачает и сразу применит последнюю OTA-версию. Для логотипа при запуске и системных функций всё ещё нужна новая APK.</p></div><button class="button button--secondary" data-action="install-ota-update">Проверить обновления</button></div>
  </section>`;
  const menuView = selected ? `<section class="admin-panel admin-menu-editor">
    <div class="admin-panel__intro"><span class="eyebrow">ЛОКАЛЬНОЕ ОФОРМЛЕНИЕ</span><h2>Витрина блюда</h2><p>Название, цена, состав и модификаторы поступают из iiko. Здесь хранятся только фото, кадрирование, бейдж и рекомендации.</p></div>
    <label class="admin-product-picker">Блюдо<select data-admin-product-select>${options(products, selected.id)}</select></label>
    <div class="admin-product-form" data-admin-product-form>
      <label>Бейдж<select data-admin-product="badge"><option value="">Без бейджа</option><option ${display[selected.id]?.badge === 'НОВИНКА' ? 'selected' : ''}>НОВИНКА</option><option ${display[selected.id]?.badge === 'ХИТ' ? 'selected' : ''}>ХИТ</option></select></label><label>Кадрирование<select data-admin-product="imagePosition"><option value="center">По центру</option><option value="top">Сверху</option><option value="bottom">Снизу</option></select></label>
      <label class="admin-product-form__wide">Ссылка на фото<input data-admin-product="image" value="${escapeHtml(selected.image)}"></label>
      <label class="admin-product-form__wide">Идеально с этим блюдом<select data-admin-product="pairs" multiple size="5">${multipleOptions(products.filter((item) => item.id !== selected.id), selected.pairs_with ?? [])}</select></label>
      <button class="button button--primary" data-action="save-product" data-product-id="${escapeHtml(selected.id)}">Сохранить блюдо</button>
    </div>
  </section>` : '';
  const promotionView = `<section class="admin-panel"><div class="admin-panel__intro"><span class="eyebrow">ГЛАВНЫЙ ЭКРАН</span><h2>Акции и витрина</h2><p>Создайте баннер или быстро включите и выключите уже созданные.</p></div><div class="promotion-create"><label>Блюдо<select data-admin-promo="productId">${options(products)}</select></label><label>Заголовок<input data-admin-promo="title" placeholder="Летний хит"></label><label>Подзаголовок<textarea data-admin-promo="subtitle" placeholder="Коротко о предложении"></textarea></label><label>Метка<input data-admin-promo="label" placeholder="НОВИНКА"></label><button class="button button--primary" data-action="create-promotion">Добавить акцию</button></div><div class="admin-promotions">${promotions.map((item) => { const product = products.find((candidate) => candidate.id === item.productId); return `<article class="admin-promo ${item.active ? '' : 'is-muted'}"><div class="admin-promo__image" ${product ? imageStyle(product.image) : ''}></div><div><span class="eyebrow">${escapeHtml(item.label)}</span><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.subtitle)}</p></div><div class="admin-promo__actions"><button class="button button--secondary button--compact" data-action="toggle-promotion-server" data-promotion-id="${item.id}">${item.active ? 'Скрыть' : 'Показать'}</button><button class="button button--primary button--compact" data-action="delete-promotion-server" data-promotion-id="${item.id}">Удалить</button></div></article>`; }).join('')}</div></section>`;
  const qualityView = `<section class="admin-panel"><div class="admin-panel__intro"><span class="eyebrow">КОНТРОЛЬ ПЕРЕД ПУБЛИКАЦИЕЙ</span><h2>Проверка меню</h2><p>Список полей, которые стоит заполнить до обновления витрины.</p></div><div class="quality-grid"><article><strong>${stats.description}</strong><span>без описания</span></article><article><strong>${stats.kbju}</strong><span>без КБЖУ</span></article><article><strong>${stats.pairs}</strong><span>без рекомендаций</span></article></div></section>`;
  const staffView = `<section class="admin-panel"><div class="admin-panel__intro"><span class="eyebrow">СОТРУДНИКИ I I K O</span><h2>Официанты</h2><p>Сотрудники приходят из iiko. Для входа в приложение задайте отдельный PIN — кассовый PIN iiko не используется.</p></div><div class="admin-staff-actions"><button class="button button--secondary" data-action="sync-iiko-employees">Обновить из iiko</button></div><div class="promotion-create"><label>Сотрудник iiko<select data-admin-waiter="employee">${employees.filter((item) => item.is_active).map((item) => `<option value="${escapeHtml(item.employee_id)}">${escapeHtml(item.display_name)}${item.role_name ? ` · ${escapeHtml(item.role_name)}` : ''}</option>`).join('') || '<option value="">Сначала обновите список iiko</option>'}</select></label><label>PIN для приложения<input data-admin-waiter="pin" inputmode="numeric" maxlength="8" placeholder="4–8 цифр"></label><button class="button button--primary" data-action="save-waiter">Выдать доступ</button></div><div class="audit-list">${waiters.length ? waiters.map((item) => `<article><b>${escapeHtml(item.display_name)}</b><span>${item.role_name ? `${escapeHtml(item.role_name)} · ` : ''}${item.is_active ? 'доступ активен' : 'доступ отключён'}</span><div><input data-waiter-pin="${escapeHtml(item.id)}" inputmode="numeric" maxlength="8" placeholder="Новый PIN"><button class="button button--secondary button--compact" data-action="update-waiter" data-waiter-id="${escapeHtml(item.id)}" data-waiter-active="${item.is_active ? 'true' : 'false'}">Сохранить</button><button class="button button--secondary button--compact" data-action="toggle-waiter" data-waiter-id="${escapeHtml(item.id)}" data-waiter-active="${item.is_active ? 'false' : 'true'}">${item.is_active ? 'Отключить' : 'Включить'}</button></div></article>`).join('') : '<div class="empty-state">Доступ официантам ещё не выдан.</div>'}</div></section>`;
  const auditView = `<section class="admin-panel"><div class="admin-panel__intro"><span class="eyebrow">ПРОЗРАЧНОСТЬ</span><h2>Последние изменения</h2><p>Журнал действий сотрудников на этом сервере.</p></div><div class="audit-list">${audit.length ? audit.map((item) => `<article><b>${escapeHtml(item.action)}</b><span>${escapeHtml(item.entity)} · ${escapeHtml(item.entity_id)}</span><time>${new Date(item.created_at).toLocaleString('ru-RU')}</time></article>`).join('') : '<div class="empty-state">Журнал загрузится после первого изменения.</div>'}</div></section>`;
  const views = { terminal: terminalView, menu: menuView, promotions: promotionView, staff: staffView, quality: qualityView, audit: auditView };
  return `<section class="admin-page"><header class="admin-header"><div><span class="eyebrow">УПРАВЛЕНИЕ РЕСТОРАНОМ</span><h1>Админ-<em>панель</em></h1><p>Все изменения сохраняются на сервере и применяются на терминалах.</p></div><button class="button button--secondary button--compact admin-logout" data-action="logout-admin">Выйти</button></header><nav class="admin-tabs">${tabs.map(([id, title]) => `<button data-action="select-admin-tab" data-admin-tab="${id}" class="${tab === id ? 'is-active' : ''}">${title}</button>`).join('')}</nav>${views[tab]}</section>`;
}
