import type { AdminDiagnostics, AdminOrder, AdminPromotion, ApplicationDownloadIssue, Banner, IikoConnectionConfig, IikoConnectionDiscovery, IikoDiscountOption, IikoRestaurantOptions, Product, ProductDisplaySettings, RestaurantTable, SecurityOverview, TableQrCode, TerminalSettings } from '../types/menu';
import type { ImageCacheState } from '../services/image-cache-service';
import type { IikoFrontOverview } from '../services/api-service';
import { escapeHtml, formatPrice } from '../utils/helpers';
import { icon } from '../components/icons';

export type AdminUpdateState = {
  phase: 'idle' | 'checking' | 'available' | 'current' | 'downloading' | 'applying' | 'error';
  currentVersion: string;
  latestVersion: string | null;
  progress: number;
  browser: boolean;
};

type AdminTab = 'terminal' | 'orders' | 'menu' | 'banners' | 'qr' | 'applications' | 'promotions' | 'staff' | 'quality' | 'security' | 'audit';
const tabs: Array<[AdminTab, string]> = [['terminal', 'Терминал'], ['orders', 'Заказы'], ['menu', 'Витрина'], ['banners', 'Баннеры'], ['qr', 'QR-коды'], ['applications', 'Приложения'], ['promotions', 'Промокоды'], ['staff', 'Сотрудники'], ['quality', 'Проверка iiko'], ['security', 'Безопасность'], ['audit', 'Журнал']];
const productLabel = (item: Product) => `${item.sku ? `${item.sku} · ` : ''}${item.category} · ${item.name}`;
const options = (products: Product[], selected = '') => products.map((item) => `<option value="${escapeHtml(item.id)}" ${item.id === selected ? 'selected' : ''}>${escapeHtml(productLabel(item))}</option>`).join('');
const multipleOptions = (products: Product[], selected: string[] = []) => products.map((item) => `<option value="${escapeHtml(item.id)}" ${selected.includes(item.id) ? 'selected' : ''}>${escapeHtml(productLabel(item))}</option>`).join('');
const missing = (products: Product[]) => {
  const skus = products.map((item) => item.sku?.trim() ?? '').filter(Boolean);
  const hasKbju = (item: Product) => item.kbju && [item.kbju.calories, item.kbju.protein, item.kbju.fat, item.kbju.carbs].some((value) => Number(value ?? 0) > 0);
  return { description: products.filter((item) => !item.description).length, composition: products.filter((item) => !item.composition?.trim()).length, kbju: products.filter((item) => !hasKbju(item)).length, pairs: products.filter((item) => !item.pairs_with?.length).length, sku: products.length - skus.length, duplicateSku: skus.length - new Set(skus).size };
};
const localDateTime = (value: string | null) => {
  if (!value) return '';
  const date = new Date(value);
  return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16);
};

type Waiter = { id: string; display_name: string; is_active: boolean; auth_source: 'local' | 'iiko'; iiko_employee_id: string | null; created_at: string };
type AdminUser = { id: string; username: string; display_name: string; role: 'administrator' | 'hostess'; is_active: boolean; created_at: string };
const statusNames = ['Принят', 'На кухне', 'Готовится', 'Готов', 'Подан'];
const compactDate = (value: string | null) => value ? new Date(value).toLocaleString('ru-RU', { day: '2-digit', month: '2-digit', hour: '2-digit', minute: '2-digit' }) : 'событий ещё не было';
const uptime = (seconds: number) => seconds >= 86400 ? `${Math.floor(seconds / 86400)} дн.` : seconds >= 3600 ? `${Math.floor(seconds / 3600)} ч.` : `${Math.max(1, Math.floor(seconds / 60))} мин.`;
const updateVersion = (value: string | null) => {
  if (!value) return '—';
  const numbered = value.match(/^0\.1\.0-(\d+)$/);
  if (numbered) return `0.1.0 · сборка ${numbered[1]}`;
  if (/^[a-f0-9]{12,}$/i.test(value)) return `Сборка ${value.slice(0, 7)}`;
  return value;
};
const updateMessage = (state: AdminUpdateState) => {
  if (state.phase === 'checking') return 'Проверяем наличие новой версии…';
  if (state.phase === 'available') return 'Новая версия готова к установке';
  if (state.phase === 'downloading') return `Загружаем обновление — ${state.progress}%`;
  if (state.phase === 'applying') return 'Устанавливаем обновление…';
  if (state.phase === 'error') return 'Не удалось проверить обновление. Проверьте интернет и повторите.';
  if (state.phase === 'current') return state.browser ? 'В браузере открыта актуальная версия' : 'Установлена последняя версия';
  return 'Нажмите «Проверить», чтобы найти новую версию';
};
const cacheBytes = (bytes: number) => bytes >= 1024 * 1024 ? `${(bytes / 1024 / 1024).toFixed(bytes >= 10 * 1024 * 1024 ? 0 : 1)} МБ` : bytes >= 1024 ? `${Math.round(bytes / 1024)} КБ` : `${bytes} Б`;
const cacheStatus = (state: ImageCacheState) => {
  if (state.phase === 'scanning') return 'Проверяем изображения…';
  if (state.phase === 'downloading') return `Загружаем: ${state.cached} из ${state.total}`;
  if (state.phase === 'clearing') return 'Очищаем хранилище…';
  if (state.phase === 'error') return `Загрузка завершена с ошибками: ${state.failed}`;
  if (state.total && state.cached === state.total) return 'Все изображения доступны на планшете';
  if (!state.total) return 'В меню пока нет изображений для загрузки';
  return `Ожидают загрузки: ${state.total - state.cached}`;
};
export function adminPage(products: Product[], banners: Banner[], display: Record<string, ProductDisplaySettings>, terminal: TerminalSettings | null, tab: AdminTab, selectedId: string | null, audit: Array<{ action: string; entity: string; entity_id: string; created_at: string }> = [], scope: 'terminal' | 'restaurant' | null = 'restaurant', role: 'administrator' | 'hostess' | 'terminal_manager' | null = 'administrator', waiters: Waiter[] = [], adminUsers: AdminUser[] = [], orders: AdminOrder[] = [], orderFilter: 'active' | 'all' = 'active', diagnostics: AdminDiagnostics | null = null, iikoConfig: IikoConnectionConfig | null = null, iikoDiscovery: IikoConnectionDiscovery | null = null, iikoOptions: IikoRestaurantOptions | null = null, selectedOrganizationId = '', promotions: AdminPromotion[] = [], iikoDiscounts: IikoDiscountOption[] = [], updateState: AdminUpdateState = { phase: 'idle', currentVersion: '—', latestVersion: null, progress: 0, browser: false }, tables: RestaurantTable[] = [], imageCache: ImageCacheState = { phase: 'idle', total: 0, cached: 0, bytes: 0, completed: 0, pending: 0, failed: 0, current: '', autoUpdate: false, lastSync: null, native: false }, qrCodes: TableQrCode[] = [], security: SecurityOverview | null = null, iikoFront: IikoFrontOverview | null = null, applicationDownloads: ApplicationDownloadIssue[] = []) {
  const selected = products.find((item) => item.id === selectedId) ?? products[0];
  const stats = missing(products);
  const legacyFixedTable = terminal?.tableSource === 'admin' && !terminal.tableId ? tables.find((item) => item.number === terminal.tableNumber) : undefined;
  const selectedTableId = terminal?.tableSource === 'admin' ? (terminal.tableId || legacyFixedTable?.id || '') : '';
  const selectedTable = tables.find((item) => item.id === selectedTableId);
  const activeWaiters = waiters.filter((item) => item.is_active);
  const selectedWaiter = activeWaiters.find((item) => item.id === terminal?.waiterId);
  const tableGroups = new Map<string, RestaurantTable[]>();
  tables.forEach((item) => tableGroups.set(item.section || 'Зал', [...(tableGroups.get(item.section || 'Зал') ?? []), item]));
  const tablePicker = `<section class="terminal-table-picker">
    <header><div><span class="eyebrow">СХЕМА ИЗ IIKO</span><h3>Стол планшета</h3><p>Закрепите планшет за конкретным столом или оставьте выбор гостю перед заказом.</p></div><div class="terminal-table-tools"><label class="terminal-table-search"><span>Поиск</span><input data-action="filter-admin-tables" placeholder="Номер, название или зал"></label><button class="button button--secondary button--compact" data-action="refresh-terminal-tables">Обновить</button></div></header>
    <input type="hidden" data-admin-terminal="tableId" value="${escapeHtml(selectedTableId)}"><input type="hidden" data-admin-terminal="tableNumber" value="${escapeHtml(selectedTable?.number ?? (terminal?.tableSource === 'admin' ? terminal.tableNumber : ''))}">
    <button class="terminal-table-auto ${selectedTableId ? '' : 'is-selected'}" data-action="select-admin-terminal-table" data-table-id="" data-table-number="" aria-pressed="${selectedTableId ? 'false' : 'true'}"><span>ВЫБОР ПЕРЕД ЗАКАЗОМ</span><strong>Стол выбирает гость</strong><small>После завершения заказа выбор автоматически сбросится</small><i></i></button>
    <div class="terminal-table-groups">${tables.length ? [...tableGroups.entries()].map(([section, items]) => `<section class="terminal-table-group" data-table-section><h4>${escapeHtml(section)}</h4><div>${items.map((item) => { const active = item.id === selectedTableId; const search = `${item.number} ${item.name} ${item.section}`.toLocaleLowerCase('ru-RU'); return `<button class="terminal-table-card ${active ? 'is-selected' : ''}" data-action="select-admin-terminal-table" data-table-id="${escapeHtml(item.id)}" data-table-number="${escapeHtml(item.number)}" data-table-search="${escapeHtml(search)}" aria-pressed="${active ? 'true' : 'false'}"><span>СТОЛ</span><strong>№${escapeHtml(item.number || item.name)}</strong>${item.name && item.name !== item.number ? `<small>${escapeHtml(item.name)}</small>` : '<small>Стол iiko</small>'}<i></i></button>`; }).join('')}</div></section>`).join('') : '<div class="terminal-table-empty">Столы пока не получены из iiko. Проверьте подключение и повторите вход в админку.</div>'}</div>
  </section>`;
  const waiterPicker = `<section class="terminal-waiter-picker">
    <header><div><span class="eyebrow">ОТВЕТСТВЕННЫЙ СОТРУДНИК</span><h3>Официант планшета</h3><p>Заказы и вызовы с этого планшета будут доступны только выбранному официанту.</p></div></header>
    <label>Ответственный официант<select data-admin-terminal="waiterId"><option value="">Не назначен · общий режим</option>${activeWaiters.map((item) => `<option value="${escapeHtml(item.id)}" ${item.id === terminal?.waiterId ? 'selected' : ''}>${escapeHtml(item.display_name)}${item.auth_source === 'iiko' ? ' · iiko' : ''}</option>`).join('')}</select></label>
    <small>${activeWaiters.length ? 'При общем режиме события видят все активные официанты.' : 'Сначала добавьте сотрудника в браузерной админке, раздел «Сотрудники».'}</small>
  </section>`;
  const cacheBusy = imageCache.phase === 'scanning' || imageCache.phase === 'downloading' || imageCache.phase === 'clearing';
  const cachePercent = imageCache.total ? Math.round(imageCache.cached / imageCache.total * 100) : 0;
  const imageCacheView = `<section class="admin-image-cache" data-cache-phase="${imageCache.phase}">
    <header><div><span class="eyebrow">ХРАНИЛИЩЕ ПЛАНШЕТА</span><h3>Кэш изображений</h3><p>Фото блюд, модификаторов и баннеры сохраняются на устройстве и открываются без повторной загрузки.</p></div><label class="admin-switch admin-image-cache__auto"><input type="checkbox" data-action="toggle-image-cache-auto" ${imageCache.autoUpdate ? 'checked' : ''} ${cacheBusy ? 'disabled' : ''}><span></span> Обновлять автоматически</label></header>
    <div class="admin-image-cache__metrics"><article><span>ЗАГРУЖЕНО</span><strong>${imageCache.cached} / ${imageCache.total}</strong></article><article><span>ЗАНЯТО</span><strong>${cacheBytes(imageCache.bytes)}</strong></article><article><span>ПОСЛЕДНЯЯ СИНХРОНИЗАЦИЯ</span><strong>${imageCache.lastSync ? compactDate(imageCache.lastSync) : 'Ещё не выполнялась'}</strong></article></div>
    <div class="admin-image-cache__status"><div><span data-image-cache-status>${escapeHtml(cacheStatus(imageCache))}</span><b data-image-cache-percent>${cachePercent}%</b></div><div class="admin-image-cache__progress"><i data-image-cache-progress style="width:${cachePercent}%"></i></div></div>
    <div class="admin-image-cache__actions"><button class="button button--primary" data-action="sync-image-cache" data-cache-force="${imageCache.cached === imageCache.total && imageCache.total > 0}" ${cacheBusy || !imageCache.total ? 'disabled' : ''}>${imageCache.cached === imageCache.total && imageCache.total > 0 ? 'Обновить весь кэш' : 'Загрузить все изображения'}</button><button class="button button--secondary" data-action="check-image-cache" ${cacheBusy || !imageCache.total ? 'disabled' : ''}>Проверить изменения</button><button class="button button--secondary admin-image-cache__clear" data-action="clear-image-cache" ${cacheBusy || !imageCache.cached ? 'disabled' : ''}>Очистить кэш</button></div>
  </section>`;
  const terminalUpdateView = `<div class="admin-app-update" data-update-phase="${updateState.phase}">
      <div class="admin-app-update__head"><span class="eyebrow">ПРИЛОЖЕНИЕ</span><h3>Обновление</h3></div>
      <div class="admin-app-update__versions">
        <div><span>Установлена</span><strong>${escapeHtml(updateVersion(updateState.currentVersion))}</strong></div>
        ${updateState.latestVersion ? `<div><span>Последняя</span><strong>${escapeHtml(updateVersion(updateState.latestVersion))}</strong></div>` : ''}
      </div>
      <div class="admin-app-update__status"><span data-ota-status>${escapeHtml(updateMessage(updateState))}</span>${updateState.phase === 'downloading' || updateState.phase === 'applying' ? `<div class="admin-app-update__progress"><i data-ota-progress style="width:${updateState.phase === 'applying' ? 100 : updateState.progress}%"></i></div>` : ''}</div>
      <div class="admin-app-update__actions">
        ${updateState.phase === 'available' ? '<button class="button button--secondary" data-action="check-ota-update">Проверить снова</button><button class="button button--primary" data-action="install-ota-update">Обновить</button>' : updateState.phase === 'checking' ? '<button class="button button--secondary" disabled>Проверяем…</button>' : updateState.phase === 'downloading' ? '<button class="button button--secondary" disabled data-ota-button>Загрузка 0%</button>' : updateState.phase === 'applying' ? '<button class="button button--secondary" disabled>Устанавливаем…</button>' : `<button class="button button--secondary" data-action="check-ota-update">${updateState.phase === 'error' ? 'Повторить' : 'Проверить'}</button>`}
      </div>
    </div>`;
  const terminalSectionIds = ['general', 'table', 'waiter', 'images', 'update'];
  const storedTerminalSection = sessionStorage.getItem('bb-terminal-settings-section') ?? 'general';
  const terminalSection = terminalSectionIds.includes(storedTerminalSection) ? storedTerminalSection : 'general';
  const terminalSectionButton = (id: string, title: string, subtitle: string, iconName: Parameters<typeof icon>[0]) => `<button data-action="select-terminal-settings-section" data-terminal-settings-target="${id}" class="${terminalSection === id ? 'is-active' : ''}" aria-label="${title}" aria-pressed="${terminalSection === id}">${icon(iconName)}<span><b>${title}</b><small>${subtitle}</small></span></button>`;
  const terminalSave = '<button class="button button--primary terminal-save" data-action="save-terminal">Сохранить настройки</button>';
  const terminalView = `<section class="admin-panel admin-terminal admin-terminal--sectioned">
    <div class="terminal-settings-workspace">
      <nav class="terminal-settings-nav" aria-label="Категории настроек планшета">
        ${terminalSectionButton('general', 'Основное', terminal?.isActive === false ? 'Терминал выключен' : 'Терминал активен', 'settings')}
        ${terminalSectionButton('table', 'Стол', selectedTable ? `№${escapeHtml(selectedTable.number || selectedTable.name)}` : 'Выбирает гость', 'map')}
        ${terminalSectionButton('waiter', 'Официант', escapeHtml(selectedWaiter?.display_name ?? 'Общий режим'), 'user')}
        ${terminalSectionButton('images', 'Изображения', imageCache.total ? `${imageCache.cached} из ${imageCache.total}` : 'Хранилище', 'image')}
        ${terminalSectionButton('update', 'Обновление', updateVersion(updateState.currentVersion), 'refresh')}
        <button class="terminal-settings-logout" data-action="logout-admin" aria-label="Выйти">${icon('logout')}<span><b>Выйти</b><small>Закрыть настройки</small></span></button>
      </nav>
      <div class="terminal-settings-content">
        <section class="terminal-settings-section terminal-settings-section--general" data-terminal-settings-section="general" ${terminalSection === 'general' ? '' : 'hidden'}>
          <header class="terminal-settings-section__header"><span>ОСНОВНОЕ</span><h3>Работа планшета</h3><p>Название устройства, режим работы и время ожидания гостя.</p></header>
          <div class="terminal-overview"><article><span>ПЛАНШЕТ</span><strong>${escapeHtml(terminal?.label || 'Без названия')}</strong><small>${terminal?.isActive === false ? 'Приём заказов выключен' : 'Готов принимать заказы'}</small></article><article class="${selectedTableId ? 'is-accent' : ''}"><span>РЕЖИМ СТОЛА</span><strong data-terminal-table-summary>${selectedTable ? `Стол №${escapeHtml(selectedTable.number || selectedTable.name)}` : 'Выбирает гость'}</strong><small>${selectedTable ? escapeHtml(selectedTable.section || 'Зал iiko') : 'Стол не закреплён'}</small></article><article class="${selectedWaiter ? 'is-accent' : ''}"><span>ОТВЕТСТВЕННЫЙ</span><strong data-terminal-waiter-summary>${escapeHtml(selectedWaiter?.display_name ?? 'Все официанты')}</strong><small>${selectedWaiter ? 'Личные заказы и вызовы' : 'Общий режим уведомлений'}</small></article></div>
          <div class="terminal-form terminal-settings-form">
            <label>Название планшета<input data-admin-terminal="label" value="${escapeHtml(terminal?.label ?? '')}" placeholder="Например: Основной зал"></label>
            <label>Таймаут бездействия<select data-admin-terminal="idleSeconds"><option value="45" ${(terminal?.idleSeconds ?? 45) === 45 ? 'selected' : ''}>45 секунд</option><option value="60" ${terminal?.idleSeconds === 60 ? 'selected' : ''}>1 минута</option><option value="90" ${terminal?.idleSeconds === 90 ? 'selected' : ''}>1,5 минуты</option><option value="120" ${terminal?.idleSeconds === 120 ? 'selected' : ''}>2 минуты</option></select></label>
            <label class="admin-switch"><input type="checkbox" data-admin-terminal="isActive" ${terminal?.isActive !== false ? 'checked' : ''}><span></span> Терминал принимает заказы</label>
            <label class="admin-switch admin-switch--demo"><input type="checkbox" data-admin-terminal="demoMode" ${terminal?.demoMode ? 'checked' : ''}><span></span><span><b>Демо-киоск</b><small>Сохранённое демонстрационное меню без отправки заказов в iiko.</small></span></label>
            ${terminalSave}
          </div>
        </section>
        <section class="terminal-settings-section terminal-form" data-terminal-settings-section="table" ${terminalSection === 'table' ? '' : 'hidden'}>${tablePicker}${terminalSave}</section>
        <section class="terminal-settings-section terminal-form" data-terminal-settings-section="waiter" ${terminalSection === 'waiter' ? '' : 'hidden'}>${waiterPicker}${terminalSave}</section>
        <section class="terminal-settings-section" data-terminal-settings-section="images" ${terminalSection === 'images' ? '' : 'hidden'}>${imageCacheView}</section>
        <section class="terminal-settings-section" data-terminal-settings-section="update" ${terminalSection === 'update' ? '' : 'hidden'}>${terminalUpdateView}</section>
      </div>
    </div>
  </section>`;
  const ordersView = `<section class="admin-panel admin-orders"><div class="admin-panel__intro"><span class="eyebrow">ЗАЛ И КУХНЯ</span><h2>Заказы</h2><p>Состояние заказов из приложения и iiko. Данные обновляются автоматически.</p></div>
    <div class="admin-orders__toolbar"><div class="admin-order-filters"><button class="${orderFilter === 'active' ? 'is-active' : ''}" data-action="set-admin-order-filter" data-order-filter="active">Активные</button><button class="${orderFilter === 'all' ? 'is-active' : ''}" data-action="set-admin-order-filter" data-order-filter="all">За 30 дней</button></div><button class="button button--secondary button--compact" data-action="refresh-admin-orders">Обновить</button></div>
    <div class="admin-orders__list">${orders.length ? orders.map((order) => `<article class="admin-order ${order.status === 'error' ? 'is-error' : order.completedAt ? 'is-complete' : ''}">
      <header><div><span>ЗАКАЗ</span><strong>${escapeHtml(order.id)}</strong></div><div><span>СТОЛ</span><strong>№${escapeHtml(order.tableNumber || '—')}</strong></div><time>${new Date(order.createdAt).toLocaleString('ru-RU')}</time></header>
      <div class="admin-order__status"><i style="--progress:${Math.max(0, Math.min(100, order.statusStep / 4 * 100))}%"></i><b>${order.status === 'error' ? 'ОШИБКА IIKO' : order.completedAt ? 'ЗАВЕРШЁН' : statusNames[order.statusStep] ?? 'ПРИНЯТ'}</b><span>${escapeHtml(order.creationStatus ?? '')}</span></div>
      <div class="admin-order__meta"><span>${order.source === 'qr' ? 'QR-заказ' : order.terminalLabel ? escapeHtml(order.terminalLabel) : 'Планшет'}</span><span>${order.items.reduce((sum, item) => sum + item.quantity, 0)} поз.</span><strong>${formatPrice(order.total)}</strong></div>
      <details><summary>Состав и история</summary><div class="admin-order__items">${order.items.map((line) => { const product = products.find((item) => item.id === line.productId); return `<div><span>${escapeHtml(line.customName ?? product?.name ?? line.productId)} ×${line.quantity}</span>${line.modifiers?.length ? `<small>${line.modifiers.map((modifier) => escapeHtml(modifier.name)).join(' · ')}</small>` : ''}</div>`; }).join('')}</div><ol class="admin-order__history">${order.history.map((event) => `<li><time>${new Date(event.createdAt).toLocaleTimeString('ru-RU', { hour: '2-digit', minute: '2-digit' })}</time><span>${escapeHtml(event.eventType.replaceAll('_', ' '))}</span></li>`).join('') || '<li><span>История появится при следующей смене статуса</span></li>'}</ol></details>
    </article>`).join('') : '<div class="empty-state">Заказов в выбранном разделе нет.</div>'}</div></section>`;
  const qrTables = tables.filter((table) => !qrCodes.some((code) => code.tableId === table.id));
  const activeQrCount = qrCodes.filter((code) => code.active).length;
  const qrView = `<section class="admin-panel admin-qr">
    <div class="admin-panel__intro admin-panel__intro--actions"><div><span class="eyebrow">ЗАКАЗ С ТЕЛЕФОНА</span><h2>QR-коды столов</h2><p>Гость сканирует код, сразу попадает в меню и оформляет заказ на выбранный стол iiko.</p></div><button class="button button--secondary button--compact" data-action="refresh-qr-codes">Обновить</button></div>
    <div class="admin-qr__summary"><article><span>СОЗДАНО</span><strong>${qrCodes.length}</strong></article><article><span>АКТИВНО</span><strong>${activeQrCount}</strong></article><article><span>СКАНИРОВАНИЙ</span><strong>${qrCodes.reduce((sum, code) => sum + code.scans, 0)}</strong></article></div>
    <div class="admin-qr__create"><label>Стол из iiko<select data-qr-table><option value="">Выберите стол</option>${qrTables.map((table) => `<option value="${escapeHtml(table.id)}">${escapeHtml(table.section || 'Зал')} · стол №${escapeHtml(table.number || table.name)}</option>`).join('')}</select></label><button class="button button--primary" data-action="create-qr-code" ${qrTables.length ? '' : 'disabled'}>Создать QR-код</button><button class="button button--secondary" data-action="generate-all-qr-codes">Создать для всех столов</button></div>
    <div class="admin-qr__notice"><b>БЕЗОПАСНАЯ ССЫЛКА</b><span>В QR не хранится открытый номер стола. Подписанный токен проверяется сервером, а отключённый или перевыпущенный код сразу перестаёт принимать заказы.</span></div>
    <div class="admin-qr__grid">${qrCodes.length ? qrCodes.map((code) => {
      const image = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(code.svg)}`;
      const lastScan = code.lastScannedAt ? compactDate(code.lastScannedAt) : 'Ещё не сканировали';
      return `<article class="qr-card ${code.active ? '' : 'is-disabled'}" data-qr-card="${escapeHtml(code.id)}"><div class="qr-card__image"><img src="${escapeHtml(image)}" alt="QR-код стола №${escapeHtml(code.tableNumber)}"></div><div class="qr-card__body"><span>${escapeHtml(code.sectionName || 'Зал')}</span><h3>Стол №${escapeHtml(code.tableNumber || code.tableName)}</h3><p>${escapeHtml(code.tableName && code.tableName !== code.tableNumber ? code.tableName : 'Заказ с телефона')}</p><small>${code.scans} скан. · ${escapeHtml(lastScan)}</small><div class="qr-card__state"><i></i>${code.active ? 'КОД АКТИВЕН' : 'КОД ОТКЛЮЧЁН'}</div></div><div class="qr-card__actions"><button class="button button--primary button--compact" data-action="download-qr-code" data-qr-id="${escapeHtml(code.id)}">Скачать SVG</button><button class="button button--secondary button--compact" data-action="print-qr-code" data-qr-id="${escapeHtml(code.id)}">Печать</button><button class="button button--secondary button--compact" data-action="copy-qr-link" data-qr-id="${escapeHtml(code.id)}">Копировать ссылку</button><button class="button button--secondary button--compact" data-action="regenerate-qr-code" data-qr-id="${escapeHtml(code.id)}">Перевыпустить</button><button class="button button--secondary button--compact" data-action="toggle-qr-code" data-qr-id="${escapeHtml(code.id)}" data-qr-active="${code.active ? 'false' : 'true'}">${code.active ? 'Отключить' : 'Включить'}</button></div></article>`;
    }).join('') : '<div class="empty-state">QR-кодов пока нет. Создайте код для одного стола или сразу для всего зала.</div>'}</div>
  </section>`;
  const applicationStatus: Record<ApplicationDownloadIssue['status'], string> = { issued: 'ГОТОВ К СКАЧИВАНИЮ', downloaded: 'СКАЧАН', installed: 'УСТАНОВЛЕН', revoked: 'ОТОЗВАН', expired: 'СРОК ИСТЁК' };
  const activeApplicationDownloads = applicationDownloads.filter((item) => item.status === 'issued');
  const applicationsView = `<section class="admin-panel admin-applications">
    <div class="admin-panel__intro admin-panel__intro--actions"><div><span class="eyebrow">БЕЗОПАСНАЯ УСТАНОВКА</span><h2>Приложения</h2><p>Одноразовый QR-код открывает загрузку APK. После первого скачивания сервер закрывает ссылку и автоматически выпускает новый код.</p></div><button class="button button--secondary button--compact" data-action="refresh-application-downloads">Обновить</button></div>
    <div class="admin-applications__summary"><article><span>АКТИВНЫЕ QR</span><strong>${activeApplicationDownloads.length}</strong></article><article><span>СКАЧАНО</span><strong>${applicationDownloads.filter((item) => item.status === 'downloaded').length}</strong></article><article><span>УСТАНОВЛЕНО</span><strong>${applicationDownloads.filter((item) => item.status === 'installed').length}</strong></article></div>
    <div class="admin-applications__create"><label>Приложение<select data-application-download="kind"><option value="kiosk">BB Kiosk</option><option value="waiter">BB Waiter</option></select></label><label>Для кого / какого устройства<input data-application-download="label" placeholder="Например: планшет зала №2"></label><label>Срок действия<select data-application-download="expires"><option value="1">1 час</option><option value="8">8 часов</option><option value="24" selected>24 часа</option><option value="168">7 дней</option></select></label><button class="button button--primary" data-action="create-application-download">Выпустить QR-код</button></div>
    <div class="admin-applications__notice"><b>КАК РАБОТАЕТ</b><span>Скачивание фиксируется автоматически. Android не сообщает сайту об успешной установке APK, поэтому после проверки устройства нажмите «Подтвердить установку».</span></div>
    <div class="admin-applications__grid">${activeApplicationDownloads.length ? activeApplicationDownloads.map((item) => { const image = item.svg ? `data:image/svg+xml;charset=utf-8,${encodeURIComponent(item.svg)}` : ''; return `<article class="application-download-card"><div class="application-download-card__qr">${image ? `<img src="${escapeHtml(image)}" alt="QR-код для скачивания ${escapeHtml(item.appName)}">` : '<span>APK недоступен</span>'}</div><div class="application-download-card__body"><span>${escapeHtml(item.appName)}</span><h3>${escapeHtml(item.label)}</h3><p>${escapeHtml(item.version)} · ${item.artifactSize ? cacheBytes(item.artifactSize) : 'файл не найден'}</p><div class="application-download-card__state is-issued"><i></i>${applicationStatus[item.status]}</div><small>Действует до ${compactDate(item.expiresAt)}</small></div><div class="application-download-card__actions"><button class="button button--secondary button--compact" data-action="copy-application-download" data-application-id="${escapeHtml(item.id)}">Копировать ссылку</button><button class="button button--secondary button--compact" data-action="download-application-qr" data-application-id="${escapeHtml(item.id)}">Скачать QR</button><button class="button button--secondary button--compact" data-action="revoke-application-download" data-application-id="${escapeHtml(item.id)}">Отозвать</button></div></article>`; }).join('') : '<div class="empty-state">Активных QR-кодов нет. Выпустите код для нужного приложения.</div>'}</div>
    <h3 class="admin-section-title">История выдач</h3><div class="application-download-history">${applicationDownloads.length ? applicationDownloads.map((item) => `<article><div><span>${escapeHtml(item.appName)}</span><b>${escapeHtml(item.label)}</b><small>${escapeHtml(item.version)} · создан ${compactDate(item.createdAt)}</small></div><strong class="is-${item.status}">${applicationStatus[item.status]}</strong><time>${item.installedAt ? `Установлен ${compactDate(item.installedAt)}` : item.downloadedAt ? `Скачан ${compactDate(item.downloadedAt)}` : item.revokedAt ? `Отозван ${compactDate(item.revokedAt)}` : `До ${compactDate(item.expiresAt)}`}</time>${item.status === 'downloaded' ? `<button class="button button--primary button--compact" data-action="confirm-application-install" data-application-id="${escapeHtml(item.id)}">Подтвердить установку</button>` : ''}</article>`).join('') : '<div class="empty-state">История появится после первой выдачи.</div>'}</div>
  </section>`;
  const menuView = selected ? `<section class="admin-panel admin-menu-editor">
    <div class="admin-panel__intro"><span class="eyebrow">ЛОКАЛЬНОЕ ОФОРМЛЕНИЕ</span><h2>Витрина блюда</h2><p>Название, цена, описание и модификаторы поступают из iiko. Здесь хранятся фото, состав, кадрирование, бейдж и рекомендации.</p></div>
    <label class="admin-product-picker">Блюдо<select data-admin-product-select>${options(products, selected.id)}</select><small>SKU: ${escapeHtml(selected.sku || 'не заполнен в iiko')}</small></label>
    <div class="admin-product-form" data-admin-product-form>
      <label>Бейдж<select data-admin-product="badge"><option value="">Без бейджа</option><option ${display[selected.id]?.badge === 'НОВИНКА' ? 'selected' : ''}>НОВИНКА</option><option ${display[selected.id]?.badge === 'ХИТ' ? 'selected' : ''}>ХИТ</option></select></label><label>Кадрирование<select data-admin-product="imagePosition"><option value="center" ${display[selected.id]?.imagePosition === 'center' ? 'selected' : ''}>По центру</option><option value="top" ${display[selected.id]?.imagePosition === 'top' ? 'selected' : ''}>Сверху</option><option value="bottom" ${display[selected.id]?.imagePosition === 'bottom' ? 'selected' : ''}>Снизу</option></select></label>
      <label class="admin-product-form__wide">Фото блюда<input type="file" accept=".png,.jpg,.jpeg,.webp,image/png,image/jpeg,image/webp" data-action="upload-product-image"><small class="banner-upload-status" data-product-upload-status>PNG, JPEG или WebP · до 8 МБ</small><input type="hidden" data-admin-product="image" value="${escapeHtml(selected.image)}"></label>
      <div class="admin-product-image admin-product-form__wide" data-product-image-preview>${selected.image ? `<img src="${escapeHtml(selected.image)}" alt="">` : '<span>Фото ещё не загружено</span>'}</div>
      <label class="admin-product-form__wide">Состав на порцию<textarea data-admin-product="composition" placeholder="Например: тесто, томатный соус, моцарелла">${escapeHtml(selected.composition ?? '')}</textarea><small>Хранится в приложении и не перезаписывается при обновлении меню iiko.</small></label>
      <label class="admin-product-form__wide">Идеально с этим блюдом<select data-admin-product="pairs" multiple size="5">${multipleOptions(products.filter((item) => item.id !== selected.id), selected.pairs_with ?? [])}</select></label>
      <button class="button button--primary" data-action="save-product" data-product-id="${escapeHtml(selected.id)}">Сохранить блюдо</button>
    </div>
  </section>` : '';
  const bannerView = `<section class="admin-panel admin-banners"><div class="admin-panel__intro"><span class="eyebrow">ГЛАВНЫЙ ЭКРАН</span><h2>Баннеры</h2><p>На планшете отображается только изображение. Для рекламного баннера обязательно задайте период и лимит показов.</p></div>
    <div class="banner-create">
      <div class="banner-upload-preview" data-banner-preview="create"><span>Загрузите изображение</span></div>
      <div class="banner-form-grid">
        <label>Название в админке<input data-banner-create="name" placeholder="Например: Летнее меню"></label>
        <label>Тип<select data-banner-create="kind"><option value="restaurant">Баннер заведения</option><option value="advertising">Рекламный баннер</option></select></label>
        <label class="banner-form-grid__wide">Открывать блюдо<select data-banner-create="productId"><option value="">Без перехода к блюду</option>${options(products)}</select></label>
        <label class="banner-form-grid__wide">Файл изображения<input type="file" accept=".png,.jpg,.jpeg,.webp,image/png,image/jpeg,image/webp" data-action="upload-banner-image" data-banner-target="create"><small class="banner-upload-status" data-banner-upload-status="create">PNG, JPEG или WebP · до 8 МБ</small><input type="hidden" data-banner-create="image"></label>
        <label>Показывать с<input type="datetime-local" data-banner-create="startsAt"></label><label>Показывать до<input type="datetime-local" data-banner-create="endsAt"></label>
        <label>Лимит показов<input type="number" min="1" step="1" data-banner-create="impressionLimit" placeholder="Только для рекламы"></label><label>Порядок<input type="number" step="1" data-banner-create="sortOrder" value="0"></label>
        <button class="button button--primary banner-form-grid__wide" data-action="create-banner">Добавить баннер</button>
      </div>
    </div>
    <div class="banner-admin-list">${banners.length ? banners.map((item) => `<article class="banner-admin-card ${item.active ? '' : 'is-muted'}" data-banner-card="${escapeHtml(item.id)}">
      <div class="banner-admin-card__image"><img src="${escapeHtml(item.image)}" alt=""><span>${item.kind === 'advertising' ? 'РЕКЛАМА' : 'ЗАВЕДЕНИЕ'}</span></div>
      <div class="banner-form-grid">
        <label>Название<input data-banner-field="name" value="${escapeHtml(item.name)}"></label>
        <label>Тип<select data-banner-field="kind"><option value="restaurant" ${item.kind === 'restaurant' ? 'selected' : ''}>Баннер заведения</option><option value="advertising" ${item.kind === 'advertising' ? 'selected' : ''}>Рекламный баннер</option></select></label>
        <label class="banner-form-grid__wide">Открывать блюдо<select data-banner-field="productId"><option value="">Без перехода к блюду</option>${options(products, item.productId ?? '')}</select></label>
        <label class="banner-form-grid__wide">Заменить изображение<input type="file" accept=".png,.jpg,.jpeg,.webp,image/png,image/jpeg,image/webp" data-action="upload-banner-image" data-banner-target="${escapeHtml(item.id)}"><small class="banner-upload-status" data-banner-upload-status="${escapeHtml(item.id)}">PNG, JPEG или WebP · до 8 МБ</small><input type="hidden" data-banner-field="image" value="${escapeHtml(item.image)}"></label>
        <label>Показывать с<input type="datetime-local" data-banner-field="startsAt" value="${localDateTime(item.startsAt)}"></label><label>Показывать до<input type="datetime-local" data-banner-field="endsAt" value="${localDateTime(item.endsAt)}"></label>
        <label>Лимит показов<input type="number" min="1" step="1" data-banner-field="impressionLimit" value="${item.impressionLimit ?? ''}" placeholder="Только для рекламы"></label><label>Порядок<input type="number" step="1" data-banner-field="sortOrder" value="${item.sortOrder}"></label>
        <div class="banner-admin-card__stats"><b>${item.impressions}</b><span>${item.impressionLimit ? `из ${item.impressionLimit} показов` : 'показов'}</span></div>
        <div class="banner-admin-card__actions"><button class="button button--primary button--compact" data-action="save-banner" data-banner-id="${escapeHtml(item.id)}">Сохранить</button><button class="button button--secondary button--compact" data-action="toggle-banner" data-banner-id="${escapeHtml(item.id)}">${item.active ? 'Скрыть' : 'Показать'}</button><button class="button button--secondary button--compact" data-action="reset-banner-impressions" data-banner-id="${escapeHtml(item.id)}">Сбросить показы</button><button class="button button--secondary button--compact" data-action="delete-banner" data-banner-id="${escapeHtml(item.id)}">Удалить</button></div>
      </div>
    </article>`).join('') : '<div class="empty-state">Баннеров пока нет. Загрузите первое изображение выше.</div>'}</div>
  </section>`;
  const discountLabel = (type: 'percent' | 'fixed', value: number) => type === 'percent' ? `${value}%` : formatPrice(value);
  const promotionsView = `<section class="admin-panel admin-promotions-panel"><div class="admin-panel__intro admin-panel__intro--actions"><div><span class="eyebrow">СКИДКИ IIKO</span><h2>Промокоды</h2><p>Код создаётся здесь и связывается с реальной скидкой iiko. Поэтому стоимость на планшете и в кассе остаётся одинаковой.</p></div><button class="button button--secondary button--compact" data-action="refresh-promotions">Обновить из iiko</button></div>
    <div class="promotion-create promotion-create--codes">
      <label>Код для гостя<input data-promotion-create="code" maxlength="32" placeholder="Например: SUMMER10"></label>
      <label>Название акции<input data-promotion-create="name" maxlength="120" placeholder="Например: Летняя скидка"></label>
      <label class="admin-product-form__wide">Скидка из iiko<select data-promotion-create="iikoDiscountTypeId"><option value="">Выберите скидку</option>${iikoDiscounts.map((item) => `<option value="${escapeHtml(item.id)}">${escapeHtml(item.name)} · ${discountLabel(item.discountType, item.value)}</option>`).join('')}</select><small>${iikoDiscounts.length ? 'Доступные скидки получены из RMS через Cloud API.' : 'В iiko не найдено подходящих ручных скидок. Создайте скидку в iikoOffice и обновите раздел.'}</small></label>
      <label>Активен с<input type="datetime-local" data-promotion-create="startsAt"></label>
      <label>Активен до<input type="datetime-local" data-promotion-create="endsAt"></label>
      <label>Лимит применений<input type="number" min="1" step="1" data-promotion-create="usageLimit" placeholder="Без ограничений"></label>
      <button class="button button--primary" data-action="create-promotion" ${iikoDiscounts.length ? '' : 'disabled'}>Создать промокод</button>
    </div>
    <div class="promotion-note"><b>КУПОНЫ IIKOCARD</b><span>Это отдельный контур лояльности. Они не входят во «Внешнее меню» и подключаются отдельно, когда ресторан настроит iikoCard.</span></div>
    <div class="promotion-list">${promotions.length ? promotions.map((item) => `<article class="promotion-card ${item.active ? '' : 'is-muted'}">
      <div class="promotion-card__code"><span>ПРОМОКОД</span><strong>${escapeHtml(item.code)}</strong></div>
      <div class="promotion-card__info"><h3>${escapeHtml(item.name)}</h3><p>${escapeHtml(item.iikoDiscountName)} · <b>−${discountLabel(item.discountType, item.value)}</b></p><small>${item.startsAt ? `с ${new Date(item.startsAt).toLocaleString('ru-RU')}` : 'без даты начала'} · ${item.endsAt ? `до ${new Date(item.endsAt).toLocaleString('ru-RU')}` : 'без даты окончания'}</small></div>
      <div class="promotion-card__usage"><strong>${item.usesCount}</strong><span>${item.usageLimit ? `из ${item.usageLimit}` : 'применений'}</span></div>
      <div class="promotion-card__actions"><button class="button button--secondary button--compact" data-action="toggle-promotion" data-promotion-id="${escapeHtml(item.id)}">${item.active ? 'Отключить' : 'Включить'}</button><button class="button button--secondary button--compact" data-action="delete-promotion" data-promotion-id="${escapeHtml(item.id)}">Удалить</button></div>
    </article>`).join('') : '<div class="empty-state">Промокодов пока нет. Выберите скидку iiko и создайте первый код.</div>'}</div>
  </section>`;
  const monitorNames: Record<string, string> = { api: 'API', database: 'База данных', disk: 'Диск', iiko_order: 'Заказы iiko', iiko_sync: 'Синхронизация iiko', webhook: 'Webhook iiko' };
  const monitorCard = (title: string, ok: boolean, value: string, detail: string, warning = false) => `<article class="monitor-card ${ok ? 'is-ok' : warning ? 'is-warning' : 'is-error'}"><header><span>${title}</span><i></i></header><strong>${value}</strong><small>${detail}</small></article>`;
  const monitorView = diagnostics ? `<div class="monitor-grid">
      ${monitorCard('API', diagnostics.api.ok, 'РАБОТАЕТ', `Аптайм ${uptime(diagnostics.api.uptimeSeconds)}`)}
      ${monitorCard('БАЗА ДАННЫХ', diagnostics.database.ok, diagnostics.database.ok ? 'ДОСТУПНА' : 'ОШИБКА', `Ответ ${diagnostics.database.latencyMs} мс`)}
      ${monitorCard('ЗАКАЗЫ IIKO', diagnostics.iikoOrders.ok, diagnostics.iikoOrders.ok ? 'БЕЗ ОШИБОК' : `${diagnostics.iikoOrders.errors24h} ОШИБ.`, diagnostics.iikoOrders.lastErrorAt ? `Последняя ${compactDate(diagnostics.iikoOrders.lastErrorAt)}` : 'За последние 24 часа')}
      ${monitorCard('WEBHOOK IIKO', diagnostics.webhook.ok, diagnostics.webhook.ok ? 'РАБОТАЕТ' : `${diagnostics.webhook.errors24h} ОШИБ.`, `${diagnostics.webhook.events24h} событий за сутки · ${compactDate(diagnostics.webhook.lastEventAt)}`)}
      ${monitorCard('ДИСК СЕРВЕРА', diagnostics.disk.ok, diagnostics.disk.usedPercent === null ? 'НЕТ ДАННЫХ' : `${diagnostics.disk.usedPercent}%`, diagnostics.disk.ok ? 'Заполнение в норме' : 'Требуется освободить место', true)}
      ${monitorCard('СИНХРОНИЗАЦИЯ', diagnostics.iikoSync.ok, diagnostics.iikoSync.ok ? 'РАБОТАЕТ' : `${diagnostics.iikoSync.errors24h} ОШИБ.`, diagnostics.iikoSync.backoffUntil ? `Пауза до ${compactDate(diagnostics.iikoSync.backoffUntil)}` : `Меню обновлено ${compactDate(diagnostics.menu.updatedAt)}`, true)}
    </div><div class="monitor-incidents"><h3>События за последние 24 часа</h3>${diagnostics.incidents.length ? `<ol>${diagnostics.incidents.map((item) => `<li class="is-${item.severity}"><time>${compactDate(item.createdAt)}</time><b>${monitorNames[item.component] ?? escapeHtml(item.component)}</b><span>${escapeHtml(item.message)}</span></li>`).join('')}</ol>` : '<p>Ошибок не зарегистрировано.</p>'}</div>` : '<div class="empty-state">Загружаем состояние сервера…</div>';
  const credentialsReady = iikoConfig && iikoConfig.appIdConfigured && iikoConfig.apiLoginConfigured && iikoConfig.clientSecretConfigured;
  const credentialStep = iikoConfig ? `<section class="iiko-config is-unlocked"><header><div><span class="eyebrow">ПОДКЛЮЧЕНИЕ IIKO</span><h3>${credentialsReady ? 'Изменить подключение' : 'Подключить ресторан'}</h3><p>Введите только данные, которые выдаёт iiko. Ресторан, касса, меню и тип заказа приложение найдёт само.</p></div><span class="iiko-config__access">ДОСТУП ПОДТВЕРЖДЁН</span></header>
    <ol class="iiko-setup-steps"><li class="is-active"><b>1</b><span>Ключи доступа</span></li><li><b>2</b><span>Ресторан и меню</span></li><li><b>3</b><span>Проверка</span></li></ol>
    <div class="iiko-config__grid iiko-config__credentials">
      <label>App ID<input type="password" data-iiko-credential="appId" placeholder="${iikoConfig.appIdConfigured ? 'Уже настроен · оставьте пустым, чтобы не менять' : 'Введите App ID'}" autocomplete="new-password" spellcheck="false"></label>
      <label>API Login<input type="password" data-iiko-credential="apiLogin" placeholder="${iikoConfig.apiLoginConfigured ? 'Уже настроен · оставьте пустым, чтобы не менять' : 'Введите API Login'}" autocomplete="new-password" spellcheck="false"></label>
      <label>Client Secret<input type="password" data-iiko-credential="clientSecret" placeholder="${iikoConfig.clientSecretConfigured ? 'Уже настроен · оставьте пустым, чтобы не менять' : 'Введите Client Secret'}" autocomplete="new-password" spellcheck="false"></label>
    </div>
    <div class="iiko-option-note"><b>НАСТРОИТСЯ АВТОМАТИЧЕСКИ</b><span>Cloud API · Organization ID · Terminal Group ID · External Menu ID · тип и источник заказа · регистрация защищённого webhook</span></div>
    <div class="iiko-config__security"><b>СЕКРЕТЫ ЗАЩИЩЕНЫ</b><span>AES-256-GCM · ключи никогда не возвращаются в браузер · изменения записываются в журнал</span><small>Последнее изменение: ${compactDate(iikoConfig.updatedAt)} · ${escapeHtml(iikoConfig.configuredBy)}</small></div>
    <div class="iiko-config__result" data-iiko-test-result>Получение списка ничего не меняет в iiko и не создаёт заказ.</div>
    <div class="iiko-config__actions"><button class="button button--primary" data-action="discover-iiko-config">Получить доступные рестораны</button></div>
  </section>` : '';
  const optionStep = iikoConfig && iikoDiscovery ? `<section class="iiko-config is-unlocked"><header><div><span class="eyebrow">ПОДКЛЮЧЕНИЕ IIKO</span><h3>Выберите ресторан</h3><p>Все технические идентификаторы получены автоматически. Вы выбираете только понятные названия.</p></div><span class="iiko-config__access">КЛЮЧИ ПРИНЯТЫ</span></header>
    <ol class="iiko-setup-steps"><li class="is-complete"><b>${icon('check')}</b><span>Ключи доступа</span></li><li class="is-active"><b>2</b><span>Ресторан и меню</span></li><li><b>3</b><span>Проверка</span></li></ol>
    <div class="iiko-config__grid">
      <label class="iiko-config__wide">Ресторан<select data-iiko-organization><option value="">Выберите ресторан</option>${iikoDiscovery.organizations.map((item) => `<option value="${escapeHtml(item.id)}" ${item.id === selectedOrganizationId ? 'selected' : ''}>${escapeHtml(item.name)}${item.code && item.code !== item.name ? ` · ${escapeHtml(item.code)}` : ''}</option>`).join('')}</select></label>
      ${iikoOptions ? `<label>Касса / терминальная группа<select data-iiko-selection="terminalGroupId">${iikoOptions.terminalGroups.map((item) => `<option value="${escapeHtml(item.id)}" ${item.id === iikoOptions.recommendedTerminalGroupId ? 'selected' : ''}>${escapeHtml(item.name)}${item.address ? ` · ${escapeHtml(item.address)}` : ''}</option>`).join('')}</select></label>
      <label>Внешнее меню<select data-iiko-selection="externalMenuId">${iikoOptions.externalMenus.map((item) => `<option value="${escapeHtml(item.id)}" ${item.id === iikoOptions.recommendedExternalMenuId ? 'selected' : ''}>${escapeHtml(item.name)}</option>`).join('')}</select></label>
      <label>Тип заказа<select data-iiko-selection="orderTypeId">${iikoOptions.orderTypes.map((item) => `<option value="${escapeHtml(item.id)}" ${item.id === iikoOptions.orderTypeId ? 'selected' : ''}>${escapeHtml(item.name)}</option>`).join('')}</select><small>Выберите тип для обычного заказа гостя за столом.</small></label>
      <div class="iiko-auto-value"><span>Источник заказа</span><b>BrooklynBowl Kiosk</b><small>Установлен автоматически</small></div>` : `<div class="iiko-options-loading iiko-config__wide">${selectedOrganizationId ? 'Получаем кассы, меню и тип заказа…' : 'Сначала выберите ресторан.'}</div>`}
    </div>
    <div class="iiko-config__result" data-iiko-test-result>${iikoOptions ? 'Выполните проверку. Она читает меню, столы и стоп-лист, но не создаёт заказ.' : 'Ожидаем выбор ресторана.'}</div>
    <div class="iiko-config__actions"><button class="button button--secondary" data-action="restart-iiko-discovery">Изменить ключи</button>${iikoOptions ? '<button class="button button--secondary" data-action="test-iiko-config">Проверить подключение</button><button class="button button--primary" data-action="apply-iiko-config" disabled>Сохранить и применить</button>' : ''}</div>
  </section>` : '';
  const iikoConnectionView = iikoConfig ? (iikoDiscovery ? optionStep : credentialStep) : `<section class="iiko-config is-locked"><div class="iiko-config__lock"><span>ЗАЩИЩЁННЫЙ РАЗДЕЛ</span><h3>Настройки подключения iiko</h3><p>Повторно подтвердите пароль администратора. После этого понадобятся только App ID, API Login и Client Secret; технические настройки приложение получит самостоятельно.</p><div><input type="password" data-iiko-config-password placeholder="Пароль администратора" autocomplete="current-password"><button class="button button--secondary" data-action="unlock-iiko-config">Открыть на 5 минут</button></div></div></section>`;
  const qualityView = `<section class="admin-panel"><div class="admin-panel__intro admin-panel__intro--actions"><div><span class="eyebrow">КОНТРОЛЬ ПЕРЕД ЗАПУСКОМ</span><h2>Проверка iiko и сервера</h2><p>Текущее состояние интеграции, инфраструктуры и заполнения меню.</p></div><button class="button button--secondary button--compact" data-action="refresh-admin-diagnostics">Проверить сейчас</button></div>${monitorView}${iikoConnectionView}<h3 class="admin-section-title">Заполнение меню iiko и витрины</h3><div class="quality-grid"><article class="${stats.sku ? 'is-warning' : ''}"><strong>${stats.sku}</strong><span>без SKU</span></article><article class="${stats.duplicateSku ? 'is-warning' : ''}"><strong>${stats.duplicateSku}</strong><span>повторяющихся SKU</span></article><article class="${stats.description ? 'is-warning' : ''}"><strong>${stats.description}</strong><span>без описания iiko</span></article><article class="${stats.composition ? 'is-warning' : ''}"><strong>${stats.composition}</strong><span>без состава в витрине</span></article><article class="${stats.kbju ? 'is-warning' : ''}"><strong>${stats.kbju}</strong><span>без заполненного КБЖУ</span></article><article class="${stats.pairs ? 'is-warning' : ''}"><strong>${stats.pairs}</strong><span>без рекомендаций</span></article></div></section>`;
  const securityStatus = (value: string) => value === 'passed' ? 'ПРОЙДЕНО' : value === 'warning' ? 'ЕСТЬ ЗАМЕЧАНИЯ' : value === 'failed' ? 'ОШИБКА' : 'ЕЩЁ НЕ ЗАПУСКАЛОСЬ';
  const securityView = `<section class="admin-panel admin-security"><div class="admin-panel__intro admin-panel__intro--actions"><div><span class="eyebrow">НАДЁЖНОСТЬ И ОПОВЕЩЕНИЯ</span><h2>Безопасность</h2><p>Автоматические проверки релиза, состояние резервных копий и критичные уведомления.</p></div><button class="button button--primary button--compact" data-action="run-security-checks">Запустить проверку</button></div>
    ${security ? `<div class="security-overview">
      <article class="is-${security.automated.status}"><span>АВТОМАТИЧЕСКИЕ ТЕСТЫ</span><strong>${securityStatus(security.automated.status)}</strong><small>${security.automated.createdAt ? `${security.automated.passed} пройдено · ${security.automated.failed} ошибок · ${compactDate(security.automated.createdAt)}` : 'Запустятся перед следующей публикацией'}</small></article>
      <article class="is-${security.safeRun.status}"><span>ПРОВЕРКА СЕРВЕРА</span><strong>${securityStatus(security.safeRun.status)}</strong><small>${security.safeRun.createdAt ? `${security.safeRun.passed} проверок пройдено · ${compactDate(security.safeRun.createdAt)}` : 'Запустите безопасную проверку'}</small></article>
      <article class="is-${security.backup.status}"><span>РЕЗЕРВНАЯ КОПИЯ</span><strong>${security.backup.lastAt ? securityStatus(security.backup.status) : 'НЕ НАЙДЕНА'}</strong><small>${security.backup.lastAt ? `${security.backup.ageHours} ч. назад · ${escapeHtml(security.backup.file ?? '')}` : 'Свежая копия базы не обнаружена'}</small></article>
      <article class="${security.telegram.configured && security.telegram.enabled ? 'is-passed' : 'is-warning'}"><span>TELEGRAM</span><strong>${security.telegram.configured ? security.telegram.enabled ? 'ПОДКЛЮЧЁН' : 'ВЫКЛЮЧЕН' : 'НЕ НАСТРОЕН'}</strong><small>${security.telegram.lastSuccessAt ? `Последняя доставка ${compactDate(security.telegram.lastSuccessAt)}` : 'Тестовое сообщение ещё не отправлялось'}</small></article>
      <article class="is-${security.smoke.status}"><span>SMOKE-ТЕСТ IIKO</span><strong>${securityStatus(security.smoke.status)}</strong><small>${security.smoke.createdAt ? `${escapeHtml(security.smoke.detail)} · ${compactDate(security.smoke.createdAt)}` : escapeHtml(security.smoke.detail)}</small></article>
      <article class="is-${security.load.status}"><span>НАГРУЗОЧНАЯ ПРОВЕРКА</span><strong>${securityStatus(security.load.status)}</strong><small>${security.load.createdAt ? `${escapeHtml(security.load.detail)} · ${compactDate(security.load.createdAt)}` : escapeHtml(security.load.detail)}</small></article>
    </div><div class="security-checks"><h3>Последняя проверка сервера</h3>${security.checks.length ? `<ol>${security.checks.map((item) => `<li class="is-${item.status}"><i></i><div><b>${escapeHtml(item.name)}</b><span>${escapeHtml(item.detail)}</span></div><strong>${securityStatus(item.status)}</strong></li>`).join('')}</ol>` : '<div class="empty-state">Проверка ещё не запускалась.</div>'}</div>` : '<div class="empty-state">Загружаем сведения о безопасности…</div>'}
    <section class="security-manual-tests"><header><div><span class="eyebrow">ОТДЕЛЬНЫЕ ПРОВЕРКИ</span><h3>Smoke и нагрузка</h3><p>Нагрузка проверяет сервер и базу без заказов. Smoke создаёт помеченный тестовый заказ в iiko с отключённой печатью кухни.</p></div></header><div class="security-manual-tests__grid"><label>Тестовый стол<select data-security-smoke="tableId"><option value="">Выберите стол</option>${tables.map((item) => `<option value="${escapeHtml(item.id)}">Стол №${escapeHtml(item.number || item.name)} · ${escapeHtml(item.section)}</option>`).join('')}</select></label><label>Тестовое блюдо<select data-security-smoke="productId"><option value="">Выберите блюдо</option>${options(products)}</select></label><button class="button button--secondary" data-action="run-load-test">Проверить нагрузку</button><button class="button button--primary" data-action="run-iiko-smoke">Создать тестовый заказ iiko</button></div></section>
    <section class="telegram-settings"><header><div><span class="eyebrow">КРИТИЧНЫЕ СОБЫТИЯ</span><h3>Уведомления в Telegram</h3><p>Токен шифруется на сервере и после сохранения больше не показывается в браузере.</p></div>${security?.telegram.configured ? `<span class="telegram-settings__state">${security.telegram.chatIdMasked}</span>` : ''}</header>
      <div class="telegram-settings__form"><label>Токен бота<input type="password" data-telegram-setting="token" placeholder="${security?.telegram.configured ? 'Уже сохранён · оставьте пустым, чтобы не менять' : '123456789:AA…'}" autocomplete="new-password"></label><label>Chat ID<input data-telegram-setting="chatId" inputmode="numeric" placeholder="Например: -1001234567890"></label><label>Пароль администратора<input type="password" data-telegram-setting="password" autocomplete="current-password" placeholder="Подтвердите изменение"></label><label class="admin-switch"><input type="checkbox" data-telegram-setting="enabled" ${security?.telegram.enabled ? 'checked' : ''}><span></span> Уведомления включены</label></div>
      ${security?.telegram.lastError ? `<div class="telegram-settings__error">${escapeHtml(security.telegram.lastError)}</div>` : ''}<footer><button class="button button--primary" data-action="save-telegram-settings">Сохранить настройки</button><button class="button button--secondary" data-action="test-telegram" ${security?.telegram.configured ? '' : 'disabled'}>Отправить тест</button></footer>
    </section></section>`;
  const activeBridge = iikoFront?.bridges.find((item) => item.is_active) ?? null;
  const staffView = `<section class="admin-panel"><div class="admin-panel__intro"><span class="eyebrow">РОЛИ И ДОСТУП</span><h2>Сотрудники</h2><p>Сотрудники приложения официанта синхронизируются с iikoFront. PIN проверяет сама iiko и он не хранится на сервере.</p></div>
    <section class="admin-image-cache"><header><div><span class="eyebrow">IIKO FRONT BRIDGE</span><h3>${activeBridge ? activeBridge.connected ? 'Подключён' : 'Нет связи' : 'Не настроен'}</h3><p>${activeBridge ? `${escapeHtml(activeBridge.display_name)} · API ${escapeHtml(activeBridge.api_version || 'V8')}${activeBridge.version ? ` · версия ${escapeHtml(activeBridge.version)}` : ''}` : 'Создайте одноразовый код и укажите его в BridgeConfig.json на компьютере с iikoFront.'}</p></div><span class="telegram-settings__state">${activeBridge?.last_sync_at ? `Синхронизация ${compactDate(activeBridge.last_sync_at)}` : 'Синхронизации ещё не было'}</span></header>
      ${iikoFront?.pairing ? `<div class="terminal-overview"><article class="is-accent"><span>ОДНОРАЗОВЫЙ КОД · 15 МИНУТ</span><strong>${escapeHtml(iikoFront.pairing.code)}</strong><small>Скопируйте код в конфигурацию плагина</small></article></div>` : ''}
      <div class="admin-image-cache__actions"><button class="button button--primary" data-action="create-iiko-front-pairing">${activeBridge ? 'Подключить другой iikoFront' : 'Создать код подключения'}</button>${activeBridge ? `<button class="button button--secondary" data-action="revoke-iiko-front-bridge" data-bridge-id="${escapeHtml(activeBridge.id)}">Отключить Bridge</button>` : ''}</div>
    </section>
    <h3 class="admin-section-title">Доступ официантов из iiko</h3><div class="audit-list admin-user-list admin-waiter-list">${iikoFront?.employees.length ? iikoFront.employees.map((item) => `<article><b>${escapeHtml(item.display_name)}</b><span>${escapeHtml(item.role_names.join(', ') || 'Роль в iiko не указана')} · ${item.is_active ? 'работает в ресторане' : 'отключён в iiko'}</span><div><button class="button button--secondary button--compact" data-action="toggle-iiko-employee" data-employee-id="${escapeHtml(item.employee_id)}" data-employee-enabled="${item.app_access_enabled ? 'false' : 'true'}" ${item.is_active ? '' : 'disabled'}>${item.app_access_enabled ? 'Закрыть доступ' : 'Разрешить вход'}</button></div></article>`).join('') : '<div class="empty-state">После подключения Bridge сотрудники iiko появятся здесь автоматически.</div>'}</div>
    <h3 class="admin-section-title">Администраторы и хостес</h3><div class="promotion-create admin-user-create"><label>Имя<input data-admin-user="name" placeholder="Например: Мария"></label><label>Логин<input data-admin-user="username" placeholder="maria"></label><label>Роль<select data-admin-user="role"><option value="hostess">Хостес</option><option value="administrator">Администратор</option></select></label><label>Пароль<input type="password" data-admin-user="password" minlength="8" placeholder="Минимум 8 символов"></label><button class="button button--primary" data-action="create-admin-user">Добавить сотрудника</button></div>
    <div class="audit-list admin-user-list">${adminUsers.length ? adminUsers.map((item) => `<article data-admin-user-card="${escapeHtml(item.id)}"><b>${escapeHtml(item.display_name)}</b><span>@${escapeHtml(item.username)} · ${item.role === 'hostess' ? 'Хостес' : 'Администратор'} · ${item.is_active ? 'активен' : 'отключён'}</span><div><select data-admin-user-role><option value="hostess" ${item.role === 'hostess' ? 'selected' : ''}>Хостес</option><option value="administrator" ${item.role === 'administrator' ? 'selected' : ''}>Администратор</option></select><input type="password" data-admin-user-password placeholder="Новый пароль"><button class="button button--secondary button--compact" data-action="save-admin-user" data-user-id="${escapeHtml(item.id)}" data-user-active="${item.is_active}">Сохранить</button><button class="button button--secondary button--compact" data-action="toggle-admin-user" data-user-id="${escapeHtml(item.id)}" data-user-active="${item.is_active ? 'false' : 'true'}">${item.is_active ? 'Отключить' : 'Включить'}</button></div></article>`).join('') : '<div class="empty-state">Отдельных пользователей пока нет. Главный пароль продолжает работать.</div>'}</div>
    ${!activeBridge ? `<h3 class="admin-section-title">Резервный вход без iikoFront</h3><div class="promotion-create"><label>Имя официанта<input data-admin-waiter="name" placeholder="Например: Анна"></label><label>PIN-код<input data-admin-waiter="pin" inputmode="numeric" maxlength="8" placeholder="4–8 цифр"></label><button class="button button--primary" data-action="create-waiter">Добавить профиль</button></div><div class="audit-list admin-user-list admin-waiter-list">${waiters.filter((item) => item.auth_source === 'local').length ? waiters.filter((item) => item.auth_source === 'local').map((item) => `<article><b>${escapeHtml(item.display_name)}</b><span>${item.is_active ? 'Доступ активен' : 'Доступ отключён'}</span><div><input data-waiter-pin="${escapeHtml(item.id)}" inputmode="numeric" maxlength="8" placeholder="Новый PIN"><button class="button button--secondary button--compact" data-action="save-waiter" data-waiter-id="${escapeHtml(item.id)}">Сохранить PIN</button><button class="button button--secondary button--compact" data-action="toggle-waiter" data-waiter-id="${escapeHtml(item.id)}" data-waiter-active="${item.is_active ? 'false' : 'true'}">${item.is_active ? 'Отключить' : 'Включить'}</button></div></article>`).join('') : '<div class="empty-state">Резервные профили не созданы.</div>'}</div>` : ''}</section>`;
  const auditView = `<section class="admin-panel"><div class="admin-panel__intro"><span class="eyebrow">ПРОЗРАЧНОСТЬ</span><h2>Последние изменения</h2><p>Журнал действий сотрудников на этом сервере.</p></div><div class="audit-list">${audit.length ? audit.map((item) => `<article><b>${escapeHtml(item.action)}</b><span>${escapeHtml(item.entity)} · ${escapeHtml(item.entity_id)}</span><time>${new Date(item.created_at).toLocaleString('ru-RU')}</time></article>`).join('') : '<div class="empty-state">Журнал загрузится после первого изменения.</div>'}</div></section>`;
  const views = { terminal: terminalView, orders: ordersView, menu: menuView, banners: bannerView, qr: qrView, applications: applicationsView, promotions: promotionsView, staff: staffView, quality: qualityView, security: securityView, audit: auditView };
  const visibleTabs = scope === 'terminal' ? tabs.filter(([id]) => id === 'terminal') : role === 'hostess' ? tabs.filter(([id]) => id === 'orders' || id === 'terminal') : tabs.filter(([id]) => id !== 'terminal');
  const allowedTabIds = new Set(visibleTabs.map(([id]) => id));
  const visibleTab: AdminTab = allowedTabIds.has(tab) ? tab : (role === 'hostess' ? 'orders' : scope === 'terminal' ? 'terminal' : 'orders');
  const singleTab = visibleTabs.length === 1;
  const adminHeader = scope === 'terminal' ? '' : '<header class="admin-header"><div><span class="eyebrow">УПРАВЛЕНИЕ РЕСТОРАНОМ</span><h1>Админ-<em>панель</em></h1><p>Все изменения сохраняются на сервере и применяются на терминалах.</p></div><button class="button button--secondary button--compact admin-logout" data-action="logout-admin">Выйти</button></header>';
  return `<section class="admin-page ${singleTab ? 'admin-page--single-tab' : ''} ${scope === 'terminal' ? 'admin-page--terminal-settings' : ''}">${adminHeader}${singleTab ? '' : `<nav class="admin-tabs" aria-label="Разделы админ-панели">${visibleTabs.map(([id, title]) => `<button data-action="select-admin-tab" data-admin-tab="${id}" class="${visibleTab === id ? 'is-active' : ''}">${title}</button>`).join('')}</nav>`}${views[visibleTab]}</section>`;
}
