import type { Product, ProductDisplaySettings, Promotion, TerminalSettings } from '../types/menu';
import { escapeHtml, imageStyle } from '../utils/helpers';

type AdminTab = 'terminal' | 'menu' | 'stock' | 'promotions' | 'quality' | 'audit';
const tabs: Array<[AdminTab, string]> = [['terminal', 'Терминал'], ['menu', 'Меню'], ['stock', 'Стоп-лист'], ['promotions', 'Акции'], ['quality', 'Проверка'], ['audit', 'Журнал']];
const options = (products: Product[], selected = '') => products.map((item) => `<option value="${escapeHtml(item.id)}" ${item.id === selected ? 'selected' : ''}>${escapeHtml(item.category)} · ${escapeHtml(item.name)}</option>`).join('');
const multipleOptions = (products: Product[], selected: string[] = []) => products.map((item) => `<option value="${escapeHtml(item.id)}" ${selected.includes(item.id) ? 'selected' : ''}>${escapeHtml(item.category)} · ${escapeHtml(item.name)}</option>`).join('');
const missing = (products: Product[]) => ({ description: products.filter((item) => !item.description).length, kbju: products.filter((item) => !item.kbju).length, pairs: products.filter((item) => !item.pairs_with?.length).length });

export function adminPage(products: Product[], promotions: Promotion[], display: Record<string, ProductDisplaySettings>, terminal: TerminalSettings | null, tab: AdminTab, selectedId: string | null, audit: Array<{ action: string; entity: string; entity_id: string; created_at: string }> = []) {
  const selected = products.find((item) => item.id === selectedId) ?? products[0];
  const stats = missing(products);
  const terminalView = `<section class="admin-panel admin-terminal">
    <div class="admin-panel__intro"><span class="eyebrow">ПРИВЯЗКА ПЛАНШЕТА</span><h2>Этот терминал</h2><p>Стол сохраняется для этого планшета и автоматически добавляется к каждому заказу.</p></div>
    <div class="terminal-form">
      <label>Название планшета<input data-admin-terminal="label" value="${escapeHtml(terminal?.label ?? '')}" placeholder="Например: Основной зал"></label>
      <label>Номер стола<input data-admin-terminal="tableNumber" value="${escapeHtml(terminal?.tableNumber ?? '')}" placeholder="Например: 14" inputmode="numeric"></label>
      <label>Таймаут бездействия<select data-admin-terminal="idleSeconds"><option value="45" ${(terminal?.idleSeconds ?? 45) === 45 ? 'selected' : ''}>45 секунд</option><option value="60" ${terminal?.idleSeconds === 60 ? 'selected' : ''}>1 минута</option><option value="90" ${terminal?.idleSeconds === 90 ? 'selected' : ''}>1,5 минуты</option><option value="120" ${terminal?.idleSeconds === 120 ? 'selected' : ''}>2 минуты</option></select></label>
      <label class="admin-switch"><input type="checkbox" data-admin-terminal="isActive" ${terminal?.isActive !== false ? 'checked' : ''}><span></span> Терминал принимает заказы</label>
      <button class="button button--primary" data-action="save-terminal">Сохранить терминал</button>
    </div>
    <div class="admin-app-update"><div><span class="eyebrow">ОБНОВЛЕНИЕ ПРИЛОЖЕНИЯ</span><h3>Актуальная версия интерфейса</h3><p>Скачает и сразу применит последнюю OTA-версию. Для логотипа при запуске и системных функций всё ещё нужна новая APK.</p></div><button class="button button--secondary" data-action="install-ota-update">Проверить обновления</button></div>
  </section>`;
  const menuView = selected ? `<section class="admin-panel admin-menu-editor">
    <div class="admin-panel__intro"><span class="eyebrow">КАТАЛОГ</span><h2>Карточка блюда</h2><p>Редактируйте коммерческие данные и отображение. Изменения сразу попадают на все терминалы.</p></div>
    <label class="admin-product-picker">Блюдо<select data-admin-product-select>${options(products, selected.id)}</select></label>
    <div class="admin-product-form" data-admin-product-form>
      <label>Название<input data-admin-product="name" value="${escapeHtml(selected.name)}"></label><label>Категория<input data-admin-product="category" value="${escapeHtml(selected.category)}"></label>
      <label>Цена, ₽<input data-admin-product="price_rub" type="number" min="0" value="${selected.price_rub}"></label><label>Граммовка<input data-admin-product="portion" value="${escapeHtml(selected.portion)}"></label>
      <label>Единица<select data-admin-product="unit"><option ${selected.unit === 'гр.' ? 'selected' : ''}>гр.</option><option ${selected.unit === 'мл.' ? 'selected' : ''}>мл.</option><option ${selected.unit === 'шт.' ? 'selected' : ''}>шт.</option></select></label><label>Бейдж<select data-admin-product="badge"><option value="">Без бейджа</option><option ${display[selected.id]?.badge === 'НОВИНКА' ? 'selected' : ''}>НОВИНКА</option><option ${display[selected.id]?.badge === 'ХИТ' ? 'selected' : ''}>ХИТ</option><option ${display[selected.id]?.badge === 'ОСТРОЕ' ? 'selected' : ''}>ОСТРОЕ</option></select></label>
      <label class="admin-product-form__wide">Описание<textarea data-admin-product="description">${escapeHtml(selected.description ?? '')}</textarea></label>
      <label class="admin-product-form__wide">Ссылка на фото<input data-admin-product="image" value="${escapeHtml(selected.image)}"></label>
      <label>Аллергены<input data-admin-product="allergens" value="${escapeHtml(display[selected.id]?.allergens ?? '')}" placeholder="молоко, яйца, глютен"></label>
      <label>Острота<select data-admin-product="spicy"><option value="none" ${(display[selected.id]?.spicy ?? 'none') === 'none' ? 'selected' : ''}>Не отмечать</option><option value="mild" ${display[selected.id]?.spicy === 'mild' ? 'selected' : ''}>Слегка острое</option><option value="hot" ${display[selected.id]?.spicy === 'hot' ? 'selected' : ''}>Острое</option></select></label>
      <label>Калории<input data-admin-product="calories" value="${escapeHtml(selected.kbju?.calories ?? '')}" placeholder="ккал"></label><label>Белки<input data-admin-product="protein" value="${escapeHtml(selected.kbju?.protein ?? '')}" placeholder="г"></label><label>Жиры<input data-admin-product="fat" value="${escapeHtml(selected.kbju?.fat ?? '')}" placeholder="г"></label><label>Углеводы<input data-admin-product="carbs" value="${escapeHtml(selected.kbju?.carbs ?? '')}" placeholder="г"></label>
      <label>Соусы через запятую<input data-admin-product="sauces" value="${escapeHtml((selected.sauce_options ?? []).join(', '))}" placeholder="Барбекю, Сырный"></label><label>Цена соуса, ₽<input data-admin-product="saucePrice" type="number" min="0" value="${escapeHtml(selected.sauce_addon_price_rub ?? '')}"></label>
      <label>Добавки через запятую<input data-admin-product="addons" value="${escapeHtml((selected.addon_options ?? []).join(', '))}" placeholder="Бекон, Сыр"></label><label>Варианты вкуса<input data-admin-product="flavors" value="${escapeHtml((selected.flavor_options ?? []).join(', '))}" placeholder="Классический, Острый"></label>
      <label class="admin-product-form__wide">Идеально с этим блюдом<select data-admin-product="pairs" multiple size="5">${multipleOptions(products.filter((item) => item.id !== selected.id), selected.pairs_with ?? [])}</select></label>
      <label class="admin-switch"><input type="checkbox" data-admin-product="unavailable" ${display[selected.id]?.unavailable ? 'checked' : ''}><span></span> В стоп-листе</label>
      <button class="button button--primary" data-action="save-product" data-product-id="${escapeHtml(selected.id)}">Сохранить блюдо</button>
    </div>
  </section>` : '';
  const stockView = `<section class="admin-panel"><div class="admin-panel__intro"><span class="eyebrow">ДОСТУПНОСТЬ</span><h2>Стоп-лист</h2><p>Блюдо исчезает из заказа гостя сразу после перевода в стоп-лист.</p></div><div class="stock-list">${products.map((item) => `<button class="stock-row ${display[item.id]?.unavailable ? 'is-unavailable' : ''}" data-action="toggle-product-stock" data-product-id="${escapeHtml(item.id)}"><span ${imageStyle(item.image)}></span><b>${escapeHtml(item.name)}</b><small>${escapeHtml(item.category)}</small><em>${display[item.id]?.unavailable ? 'Вернуть в меню' : 'В стоп-лист'}</em></button>`).join('')}</div></section>`;
  const promotionView = `<section class="admin-panel"><div class="admin-panel__intro"><span class="eyebrow">ГЛАВНЫЙ ЭКРАН</span><h2>Акции и витрина</h2><p>Создайте баннер или быстро включите и выключите уже созданные.</p></div><div class="promotion-create"><label>Блюдо<select data-admin-promo="productId">${options(products)}</select></label><label>Заголовок<input data-admin-promo="title" placeholder="Летний хит"></label><label>Подзаголовок<textarea data-admin-promo="subtitle" placeholder="Коротко о предложении"></textarea></label><label>Метка<input data-admin-promo="label" placeholder="НОВИНКА"></label><button class="button button--primary" data-action="create-promotion">Добавить акцию</button></div><div class="admin-promotions">${promotions.map((item) => { const product = products.find((candidate) => candidate.id === item.productId); return `<article class="admin-promo ${item.active ? '' : 'is-muted'}"><div class="admin-promo__image" ${product ? imageStyle(product.image) : ''}></div><div><span class="eyebrow">${escapeHtml(item.label)}</span><h3>${escapeHtml(item.title)}</h3><p>${escapeHtml(item.subtitle)}</p></div><div class="admin-promo__actions"><button class="button button--secondary button--compact" data-action="toggle-promotion-server" data-promotion-id="${item.id}">${item.active ? 'Скрыть' : 'Показать'}</button><button class="button button--primary button--compact" data-action="delete-promotion-server" data-promotion-id="${item.id}">Удалить</button></div></article>`; }).join('')}</div></section>`;
  const qualityView = `<section class="admin-panel"><div class="admin-panel__intro"><span class="eyebrow">КОНТРОЛЬ ПЕРЕД ПУБЛИКАЦИЕЙ</span><h2>Проверка меню</h2><p>Список полей, которые стоит заполнить до обновления витрины.</p></div><div class="quality-grid"><article><strong>${stats.description}</strong><span>без описания</span></article><article><strong>${stats.kbju}</strong><span>без КБЖУ</span></article><article><strong>${stats.pairs}</strong><span>без рекомендаций</span></article><article><strong>${products.filter((item) => display[item.id]?.unavailable).length}</strong><span>в стоп-листе</span></article></div></section>`;
  const auditView = `<section class="admin-panel"><div class="admin-panel__intro"><span class="eyebrow">ПРОЗРАЧНОСТЬ</span><h2>Последние изменения</h2><p>Журнал действий сотрудников на этом сервере.</p></div><div class="audit-list">${audit.length ? audit.map((item) => `<article><b>${escapeHtml(item.action)}</b><span>${escapeHtml(item.entity)} · ${escapeHtml(item.entity_id)}</span><time>${new Date(item.created_at).toLocaleString('ru-RU')}</time></article>`).join('') : '<div class="empty-state">Журнал загрузится после первого изменения.</div>'}</div></section>`;
  const views = { terminal: terminalView, menu: menuView, stock: stockView, promotions: promotionView, quality: qualityView, audit: auditView };
  return `<section class="admin-page"><header class="admin-header"><div><span class="eyebrow">УПРАВЛЕНИЕ РЕСТОРАНОМ</span><h1>Админ-<em>панель</em></h1><p>Все изменения сохраняются на сервере и применяются на терминалах.</p></div><button class="button button--secondary button--compact admin-logout" data-action="logout-admin">Выйти</button></header><nav class="admin-tabs">${tabs.map(([id, title]) => `<button data-action="select-admin-tab" data-admin-tab="${id}" class="${tab === id ? 'is-active' : ''}">${title}</button>`).join('')}</nav>${views[tab]}</section>`;
}
