import './style.css';

const api = 'https://xn--80aatcn.xn--b1ajk7f.xn--p1ai/api/v1';
const root = document.querySelector<HTMLDivElement>('#app')!;
let token = localStorage.getItem('bb-waiter-token') ?? '';
let waiter = JSON.parse(localStorage.getItem('bb-waiter-profile') ?? 'null') as { id: string; name: string } | null;
let initialized = false; let known = new Set<string>();
type Request = { id:number; table_number:string; request_type:string; status:string; created_at:string };
type Order = { order_number:string; table_number:string; total:number; status_step:number; created_at:string; source:string };
const request = async <T>(path:string, init:RequestInit={}) => { const r=await fetch(`${api}${path}`,{...init,headers:{'Content-Type':'application/json',...(token?{Authorization:`Bearer ${token}`}:{})}}); const b=await r.json().catch(()=>({})); if(!r.ok) throw new Error(b.error??'Ошибка сервера'); return b as T; };
const title:Record<string,string>={waiter:'Позвать официанта',bill:'Принести счёт',cutlery:'Принести приборы',help:'Нужна помощь'};
const sound=()=>{ try { const c=new AudioContext(); const o=c.createOscillator(); const g=c.createGain(); o.frequency.value=880; g.gain.value=.12; o.connect(g);g.connect(c.destination);o.start();setTimeout(()=>{o.frequency.value=1175},180);setTimeout(()=>{o.stop();c.close()},520); }catch{} };
function login(){ root.innerHTML=`<section class="login"><span>BrooklynBowl</span><h1>Официант</h1><p>Введите персональный PIN-код.</p><input inputmode="numeric" type="password" maxlength="8" placeholder="PIN" autofocus><button>Войти</button></section>`; root.querySelector('button')!.onclick=async()=>{try{const pin=root.querySelector('input')!.value;const r=await request<{token:string;waiter:{id:string;name:string}}>('/waiter/login',{method:'POST',body:JSON.stringify({pin})});token=r.token;waiter=r.waiter;localStorage.setItem('bb-waiter-token',token);localStorage.setItem('bb-waiter-profile',JSON.stringify(waiter));initialized=false;queue()}catch(e){alert(e instanceof Error?e.message:'Ошибка')}}; }
function render(requests:Request[],orders:Order[],alert?:Request){ root.innerHTML=`<header><span>BROOKLYN BOWL</span><strong>${waiter?.name??''}</strong></header><section class="dashboard"><div class="hero"><span>СМЕНА АКТИВНА</span><h1>Ваши<br><em>задачи</em></h1><p>Новые вызовы и заказы появляются автоматически.</p></div><div class="columns"><section><h2>Вызовы</h2>${requests.length?requests.map(r=>`<article class="task ${r.status==='new'?'new':''}"><span>СТОЛ №${r.table_number}</span><h3>${title[r.request_type]??r.request_type}</h3><small>${new Date(r.created_at).toLocaleTimeString('ru-RU',{hour:'2-digit',minute:'2-digit'})}</small>${r.status==='new'?`<button data-id="${r.id}">Принять</button>`:'<b>Принято вами</b>'}</article>`).join(''):'<p class="empty">Нет новых вызовов</p>'}</section><section><h2>Активные заказы</h2>${orders.map(o=>`<article class="order"><span>СТОЛ №${o.table_number}</span><h3>${o.order_number}</h3><b>${o.total} ₽</b></article>`).join('')||'<p class="empty">Нет активных заказов</p>'}</section></div></section>${alert?`<div class="incoming"><span>НОВЫЙ ВЫЗОВ</span><h1>СТОЛ №${alert.table_number}</h1><p>${title[alert.request_type]??alert.request_type}</p><button data-id="${alert.id}">Принять вызов</button></div>`:''}`;root.querySelectorAll<HTMLButtonElement>('[data-id]').forEach(b=>b.onclick=()=>accept(Number(b.dataset.id))); }
async function accept(id:number){try{await request(`/waiter/requests/${id}/accept`,{method:'POST'});await queue()}catch(e){alert(e instanceof Error?e.message:'Не удалось принять вызов')}}
async function queue(){if(!token)return login();try{const data=await request<{requests:Request[];orders:Order[]}>('/waiter/queue');const fresh=data.requests.find(r=>r.status==='new'&&!known.has(String(r.id)));if(!initialized){data.requests.forEach(r=>known.add(String(r.id)));initialized=true}else if(fresh){known.add(String(fresh.id));sound()}render(data.requests,data.orders,fresh)}catch{localStorage.removeItem('bb-waiter-token');token='';login()}}
queue();setInterval(queue,5000);
